main: fr.assaut.moderation.Main
name: Moderation
version: 1.0
author: Raph
description: Plugin de Moderation
commands:
   mod:
      description: Outils de moderation avert ban kick mute
   report:
      description: Signaler un comportement inadequat
   herve:
      description: surprise
